name: news_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 7.0.7+27

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: any
  cloud_firestore: any
  cupertino_icons: any
  dots_indicator: any
  easy_localization: any
  firebase_auth: any
  firebase_core: any
  firebase_messaging: any
  firebase_storage: any
  flutter_web_browser: any
  flutter_html: any
  google_fonts: any
  google_sign_in: any
  html_unescape: any
  image_picker: any
  intl: any
  introduction_screen: any
  launch_review: any
  line_icons: any
  lottie: any
  package_info: any
  path_provider: any
  provider: any
  share: any
  shared_preferences: any
  skeleton_text: any
  fluttertoast: any
  url_launcher: any
  youtube_player_flutter: any
  rounded_loading_button: any
  firebase_analytics: any
  flutter_facebook_auth: any
  the_apple_sign_in: any
  hive: any
  hive_flutter: any
  jiffy: any
  loading_indicator: any
  reading_time: any
  pod_player: any
  google_mobile_ads: any
  # facebook_audience_network: ^1.0.1
  app_settings: any
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  md2_tab_indicator:
    git:
      url: https://github.com/westdabestdb/md2_tab_indicator
      



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.11.0"
  change_app_package_name: ^1.1.0



flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"



# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation_files/
    - assets/translations/

  fonts:

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500

    - family: Manrope
      fonts:
        # - asset: assets/fonts/Manrope-Light.ttf
        #   weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900
